### PR TITLE
Tokenization of written numbers

### PR DESCRIPTION
**Pull request by sultur**
- Removed multiplication of written numbers functionality.
- Fixed "dönskum krónum" bug where "krónum" is interpreted as the definite form of the word "kró".

Currently there is an issue with terminals of the form `{nationality} {currency}` (e.g. "breskra punda", "indónesískra rúpía") where their number/case is incorrectly identified. (See `test_parse.py::test_amounts`).

We may also want to add large numbers ("kvaðrilljarður" and upwards) to our BÍN vocabulary.

### CODE REVIEW

**Review by vthorsteinsson — COMMENTED** [review]
LGTM! The "kró" bug is a great find.

**Comment by sveinbjornt** [comment]
Is this good to merge, @vthorsteinsson ?

**Comment by vthorsteinsson** [comment]
There are still some commented-out currency names (bresk pund, indónesískar rúpíur) in the tests, so I'm not sure whether this is fully tested and vetted yet. @sultur

**Comment by sultur** [comment]
I wasn't quite happy with this implementation, as it overwrites the default behaviour of the BÍN tokenizer. I am working on another one which isn't as drastic and has an optional flag to turn off the functionality of combining numbers (and also fixes the kró bug). We can probably just close this pull request without merging it and I'll try to create the new pull request asap.

**Pull request closed without merging**
